### PR TITLE
Leaf/1.8 message table

### PR DESCRIPTION
**Pull request by K0725**
Initialized SQL databased and created model for django db. Still need to test the Django db model.

### CODE REVIEW

**Comment by misslame** [comment]
Looks like you have a lot of commits unrelated to your changes, are you able to rebase and branch off of dev branch to ensure commit history is only related to your changes?

**Comment by K0725** [comment]
> Looks like you have a lot of commits unrelated to your changes, are you able to rebase and branch off of dev branch to ensure commit history is only related to your changes?

OH yes I see it. I will rebase my commits in the branch to ensure my commit history to my changes

**Comment by K0725** [comment]
> Looks like you have a lot of commits unrelated to your changes, are you able to rebase and branch off of dev branch to ensure commit history is only related to your changes?

I just updated my branch with rebase.

**Comment by misslame** [comment]
I suggest because it looks like the rebase wasn't successful the following 

If you want to learn git more thoroughly and struggle a bit, try to make it so that the commits listed in the PR is only your commits through rebase. (Changing the base of your branch to current dev) 

If you're struggling too much and want to give up, make a new branch off of dev and then git cherry-pick your commits from this one or copy paste your changes woth new commit

**Comment by misslame** [comment]
We cant merge this PR till its cleaned up because it would squash all the commits or cause a diverged commit history.

**Comment by K0725** [comment]
> I suggest because it looks like the rebase wasn't successful the following
> 
> If you want to learn git more thoroughly and struggle a bit, try to make it so that the commits listed in the PR is only your commits through rebase. (Changing the base of your branch to current dev)
> 
> If you're struggling too much and want to give up, make a new branch off of dev and then git cherry-pick your commits from this one or copy paste your changes woth new commit



> I suggest because it looks like the rebase wasn't successful the following
> 
> If you want to learn git more thoroughly and struggle a bit, try to make it so that the commits listed in the PR is only your commits through rebase. (Changing the base of your branch to current dev)
> 
> If you're struggling too much and want to give up, make a new branch off of dev and then git cherry-pick your commits from this one or copy paste your changes woth new commit

Yea I still see the commits error with other commits. I will try to rebase again tomorrow as a practice, but like you said, if I stuck on the rebase, I will just create new branch and cherry pick my commits to new branch.

**Pull request closed without merging**
